version: '3.8'
services:
  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATABASE_USERNAME=root
      - SPRING_DATABASE_PASSWORD=root
    healthcheck:
      test: "wget -q localhost:9090/actuator/health -O - | grep UP || exit 1"
      interval: 2s
      timeout: 2s
      retries: 5

  db:
    image: postgres:15.4
    container_name: shareit-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: "pg_isready -q -d shareit -U postgres"
      interval: 2s
      timeout: 2s
      retries: 5